name: Deploy Streamlit App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit
        pip install pandas
        pip install plotly
        pip install openpyxl
        pip install python-docx
        pip install openai
        pip install requests
        pip install python-dotenv
        # Install from requirements.txt if it exists
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Create secrets file
      env:
        OPENAI_API_KEY: ${{ secrets.OPEN_AI }}
        OPEN_AI: ${{ secrets.OPEN_AI }}
      run: |
        echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env
        echo "OPEN_AI=$OPEN_AI" >> .env
    
    - name: Test import modules
      env:
        OPENAI_API_KEY: ${{ secrets.OPEN_AI }}
        OPEN_AI: ${{ secrets.OPEN_AI }}
      run: |
        python -c "import streamlit; print('✅ Streamlit OK')"
        python -c "import pandas; print('✅ Pandas OK')"
        python -c "import plotly.express; print('✅ Plotly OK')"
        python -c "import plotly.graph_objects; print('✅ Plotly Graph Objects OK')"
        python -c "import os; print('✅ API Key:', os.getenv('OPENAI_API_KEY', 'Not found')[:8] + '...' if os.getenv('OPENAI_API_KEY') else 'Not found')"
        python -c "print('✅ All modules imported successfully')"
    
    - name: Run Streamlit App (Test)
      env:
        OPENAI_API_KEY: ${{ secrets.OPEN_AI }}
        OPEN_AI: ${{ secrets.OPEN_AI }}
      run: |
        echo "Testing Streamlit app startup..."
        timeout 30s streamlit run main.py --server.headless true --server.port 8501 || echo "App test completed"
