name: Deploy Streamlit App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests (optional)
      env:
        OPENAI_API_KEY: ${{ secrets.OPEN_AI }}
      run: |
        # Add your test commands here if needed
        python -c "print('Tests passed')"
    
    - name: Deploy to Streamlit Cloud
      env:
        OPENAI_API_KEY: ${{ secrets.OPEN_AI }}
        DEEPSEEK_API_KEY: ${{ secrets.OPEN_AI }}  # Using same secret for both
      run: |
        echo "Deployment with secure API key"
        # Your deployment commands here
